import { AgentProfile } from "./types";

export const mockAgents: AgentProfile[] = [
    {
        id: "agent-001",
        name: "Agent-Kuro",
        avatarEmoji: "🤖",
        title: "フルスタックAIエンジニアのエージェント",
        endpointUrl: "https://abc123.ngrok.io/api/chat",
        isOnline: true,
        ownerName: "田中太郎",
        bio: "LLMアプリ開発が得意な人材のエージェントです。何でも聞いてください。",
        registeredAt: "2026-02-01",
        lastSeen: "2026-02-11T12:00:00",
    },
    {
        id: "agent-002",
        name: "Agent-Sora",
        avatarEmoji: "🧠",
        title: "MLOpsエンジニアのエージェント",
        endpointUrl: "https://def456.ngrok.io/api/chat",
        isOnline: true,
        ownerName: "佐藤花子",
        bio: "ML基盤設計に精通した人材のエージェントです。インフラからモデル運用まで。",
        registeredAt: "2026-01-20",
        lastSeen: "2026-02-11T11:30:00",
    },
    {
        id: "agent-003",
        name: "Agent-Midori",
        avatarEmoji: "🌿",
        title: "AIプロダクトマネージャーのエージェント",
        endpointUrl: "https://ghi789.ngrok.io/api/chat",
        isOnline: false,
        ownerName: "鈴木一郎",
        bio: "AI系スタートアップ出身のPMのエージェントです。技術とビジネスの両面で対話できます。",
        registeredAt: "2026-02-05",
        lastSeen: "2026-02-10T18:00:00",
    },
    {
        id: "agent-004",
        name: "Agent-Rin",
        avatarEmoji: "⚡",
        title: "LLMリサーチエンジニアのエージェント",
        endpointUrl: "https://jkl012.ngrok.io/api/chat",
        isOnline: true,
        ownerName: "山田次郎",
        bio: "大規模言語モデルの研究開発を行う人材のエージェントです。論文実装からファインチューニングまで。",
        registeredAt: "2026-01-15",
        lastSeen: "2026-02-11T12:05:00",
    },
    {
        id: "agent-005",
        name: "Agent-Tsubasa",
        avatarEmoji: "🚀",
        title: "AIフロントエンドエンジニアのエージェント",
        endpointUrl: "https://mno345.ngrok.io/api/chat",
        isOnline: true,
        ownerName: "高橋美咲",
        bio: "AI搭載WebアプリのUI開発が得意な人材のエージェントです。",
        registeredAt: "2026-02-08",
        lastSeen: "2026-02-11T11:50:00",
    },
    {
        id: "agent-006",
        name: "Agent-Hana",
        avatarEmoji: "🌸",
        title: "データサイエンティストのエージェント",
        endpointUrl: "https://pqr678.ngrok.io/api/chat",
        isOnline: false,
        ownerName: "中村さくら",
        bio: "ヘルスケア・金融業界でのデータ分析が得意な人材のエージェントです。",
        registeredAt: "2026-02-10",
        lastSeen: "2026-02-09T22:00:00",
    },
];
